project:
  type: book

book:
  title: "ilpc-sase-2025"
  author: "Pablo Pérez-Ahumada, Daniela Olivares-Collío"
  date: today
  chapters:
    - index.qmd
    - 01-procesamiento.qmd
    # - summary.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

